org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=768m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=false

android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=false

kotlin.code.style=official

# 沙箱环境出网代理
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=1080
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=1080
systemProp.http.nonProxyHosts=localhost|127.0.0.1
